[package]
name = "blog_puller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.11.14", features = ["blocking"]}
rss = "2.0.2"
regex = "1.7.1"
chrono = "0.4.23"
