name: Update Profile README Everyday

on:
  schedule:
    - cron:  '0 0 * * *'
  
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Download binary
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        name: blog_puller_bin

    - name: Run
      run: ./blog_puller_bin