name: Update Profile README Everyday

on:
  schedule:
    - cron:  '0 0 * * *'
  
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Blog_It
      uses: Azanul/BlogIt@test4
